[telegram]
api_token = "token"
chat_id = "id"

[features]
# 新帖推送开关
v2ex_fetch_latest = true
# 新帖推送关键字过滤
v2ex_fetch_latest_keyword = ["键盘", "大模型"]
# 热帖推送开关
v2ex_fetch_hot = true
# hacker news top贴推送开关
hn_fetch_top = false
hn_fetch_latest=false
# 仅解析前5个的hacker news top帖子
hn_fetch_num = 5
# hacker news目标帖子距今时间（hacker news的top算法可能导致大量新帖冒出） 单位:H
hn_fetch_time_gap = 8

[deepseek]
api_token="key"
